databases:
  - name: today_band
    plan: free
    databaseName: today_band
    user: today_band
    region: singapore
services:
  - type: web
    plan: free
    name: today_band
    runtime: python
    region: singapore
    buildCommand: './build.sh'
    startCommand: 'python -m gunicorn today_band.asgi:application -k uvicorn.workers.UvicornWorker'
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: today_band
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
