databases:
  - name: todayband-db
    plan: free
    databaseName: todayband
    user: todayband
    region: singapore
services:
  - type: web
    plan: free
    name: today-band-backend
    runtime: python
    region: singapore
    buildCommand: './build.sh'
    startCommand: 'gunicorn config.asgi:application -k uvicorn.workers.UvicornWorker'
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: todayband-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
