# Generated by Django 5.1.3 on 2024-12-11 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Band',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('photo', models.TextField(null=True)),
                ('formation_date', models.CharField(max_length=10)),
                ('debut_date', models.CharField(max_length=10)),
                ('members', models.TextField()),
                ('member_photos', models.TextField(null=True)),
                ('member_info', models.TextField(null=True)),
                ('hit_songs', models.CharField(max_length=255)),
                ('introduction', models.TextField(null=True)),
                ('music_photo', models.TextField(null=True)),
                ('albums', models.TextField()),
                ('awards', models.TextField()),
                ('classification', models.CharField(choices=[('ga', '가'), ('na', '나'), ('da', '다'), ('ra', '라'), ('ma', '마'), ('ba', '바'), ('sa', '사'), ('ah', '아'), ('ja', '자'), ('cha', '차'), ('ka', '카'), ('ta', '타'), ('pa', '파'), ('ha', '하')], default='ga', max_length=3)),
            ],
            options={
                'verbose_name_plural': 'bands',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
    ]
