# Generated by Django 5.1.3 on 2024-12-04 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Band',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('photo', models.URLField()),
                ('formation_date', models.CharField(max_length=10)),
                ('debut_date', models.CharField(max_length=10)),
                ('members', models.TextField()),
                ('hit_songs', models.CharField(max_length=255)),
                ('albums', models.TextField()),
                ('awards', models.TextField()),
                ('genre', models.ManyToManyField(to='bands.genre')),
            ],
            options={
                'verbose_name_plural': 'bands',
            },
        ),
    ]
