# Generated by Django 5.1.3 on 2024-12-03 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterModelOptions(
            name='bands',
            options={'verbose_name_plural': 'bands'},
        ),
        migrations.RemoveField(
            model_name='bands',
            name='genre',
        ),
        migrations.AddField(
            model_name='bands',
            name='genre',
            field=models.ManyToManyField(to='bands.genre'),
        ),
    ]
