# Generated by Django 5.1.3 on 2024-12-13 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='band',
            name='user',
        ),
    ]
