# Generated by Django 5.1.3 on 2024-12-04 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0002_band_classification'),
    ]

    operations = [
        migrations.AddField(
            model_name='band',
            name='music_links',
            field=models.TextField(null=True),
        ),
    ]
