# Generated by Django 5.1.3 on 2024-12-04 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0003_band_music_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='band',
            name='music_photo',
            field=models.TextField(null=True),
        ),
    ]
