# Generated by Django 5.1.3 on 2024-12-06 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0004_band_music_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='band',
            name='music_links',
        ),
        migrations.AddField(
            model_name='band',
            name='introduction',
            field=models.TextField(null=True),
        ),
    ]
