# Generated by Django 5.1.3 on 2024-12-06 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0005_remove_band_music_links_band_introduction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='band',
            name='photo',
            field=models.TextField(null=True),
        ),
    ]
