# Generated by Django 5.1.3 on 2024-12-06 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0007_band_member_photos'),
    ]

    operations = [
        migrations.AddField(
            model_name='band',
            name='member_info',
            field=models.TextField(null=True),
        ),
    ]
